# Use root/example as user/password credentials
version: '3.8'

services:
  cliente:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - network

  server:
    image: tupfrcutn/elecciones-2023:1.0.0
    ports:
      - "8080:8080"
    networks:
      - network

networks:
  network: